import { createContext, useContext, useEffect, useMemo, useState, type ReactNode } from "react";

export type Language = "de" | "en";
type Variables = Record<string, string | number>;

const de: Record<string, string> = {
  overview: "Übersicht", allModels: "Alle Modelle", libraries: "Libraries", noFolders: "Noch keine Ordner hinzugefügt.", addLibrary: "Library hinzufügen", dropFolder: "Ordner hier ablegen", recursiveScan: "Unterordner werden automatisch durchsucht.", search: "Modelle durchsuchen …", aiCreate: "KI erstellen", convert: "Konvertieren", refreshLibraries: "Libraries neu einlesen", gallerySettings: "Gallery-Einstellungen", scanning: "Bibliotheken werden eingelesen …", model: "Modell", models: "Modelle", sort: "Sortieren", sortName: "Name", sortNewest: "Zuletzt geändert", sortLargest: "Dateigröße", sortColors: "Anzahl Farben", sortHue: "Dominante Farbe", sortSimilar: "Ähnliche Farbe", referenceColor: "Referenzfarbe", chooseSimilarColor: "Farbe wählen und ähnliche Modelle zuerst anzeigen", libraryReadError: "Eine Library konnte nicht gelesen werden: {message}", galleryPages: "Galerieseiten", previous: "Zurück", next: "Weiter", pageOf: "Seite {page} von {pages}", rangeOf: "{from}–{to} von {total}", loadingMore: "Weitere Modelle werden geladen …", shownOf: "{shown} von {total} Modellen", noMatches: "Keine passenden Modelle", noVox: "Keine .vox-Dateien gefunden", collectionStarts: "Deine Voxel-Sammlung beginnt hier", trySearch: "Versuche einen anderen Suchbegriff.", addFilesHint: "Lege .vox-Dateien im Library-Ordner ab und lies ihn erneut ein.", addFolderHint: "Füge einen Windows-Ordner hinzu oder ziehe ihn direkt in dieses Fenster.", firstFolder: "Ersten Ordner auswählen", dropAdd: "Library-Ordner hinzufügen", releaseNow: "Jetzt loslassen", settings: "Einstellungen", close: "Schließen", hideUnreadable: "Nicht lesbare Dateien ausblenden", hideUnreadableInfo: "Dateien mit Parser- oder Vorschaufehlern verschwinden nach der Prüfung aus der Galerie.", infiniteScroll: "Unendliches Scrollen", infiniteScrollInfo: "Weitere Modelle werden beim Scrollen automatisch geladen; die Seitennavigation entfällt.", language: "Sprache", languageInfo: "Sprache der gesamten Benutzeroberfläche auswählen.", german: "Deutsch", english: "English", unreadableStatus: "{count} nicht lesbare {files} in dieser Sitzung erkannt", file: "Datei", files: "Dateien", done: "Fertig", libraryAdded: "Library wurde hinzugefügt.", librariesAdded: "{count} Libraries wurden hinzugefügt.", saved: "Gespeichert: {path}", converted: "Konvertiert: {path}", folderDialog: "Library-Ordner auswählen",
  noPreview: "Keine Vorschau", preview: "Vorschau …", libraryRoot: "Library-Stamm", usedColorsTitle: "{count} verwendete Farben",
  cameraViews: "Kameraansichten", front: "Vorne", back: "Hinten", left: "Links", right: "Rechts", top: "Oben", bottom: "Unten", center: "Zentrieren", grid: "Raster", autoRotate: "Auto-Rotation", viewerHelp: "Ziehen: drehen · Mausrad: zoomen · Rechtsklick: verschieben", viewAsset: "{name} ansehen", palette: "Palette", inExplorer: "Im Explorer", closeViewer: "Viewer schließen", usedColors: "Verwendete Farben", voxels: "Voxel", openFailed: "Modell konnte nicht geöffnet werden", loadingModel: "Modell wird geladen …",
  aiWorkshop: "KI-Werkstatt", newVoxelModel: "Neues Voxelmodell", generator: "Generator", closeGenerator: "Generator schließen", description: "Beschreibung", describeModel: "Beschreibe dein Voxelmodell …", scoutRobot: "Scout-Roboter", villageHouse: "Dorfhaus", starterPrompt: "Ein uralter, moosbewachsener Waldschrein mit einem türkis leuchtenden Kristall. Stilisiert und als Game-Asset gut lesbar.", scoutPrompt: "Ein kleiner futuristischer Scout-Roboter mit hellem Visier und orangenen Details.", housePrompt: "Ein gemütliches mittelalterliches Dorfhaus mit rotem Dach und blauen Fenstern.", modelSize: "Modellgröße", refinePrompt: "Prompt verfeinern", detailSimple: "Einfach · klare Low-Poly-Form", detailBalanced: "Ausgewogen · mittlere Details", detailDetailed: "Detailliert · komplexe Oberfläche", extraInstructions: "Zusätzliche Stil-, Farb- oder Formvorgaben …", modelProvider: "Modellanbieter", customProvider: "Eigener", compatible: "Ollama / kompatibel", endpoint: "Endpoint", apiKey: "API-Key", optional: "Optional", rememberKey: "Key lokal auf diesem Gerät speichern", shapingVoxels: "Voxel werden geformt …", generateModel: "Modell generieren", readyIdea: "Bereit für deine Idee", previewAppears: "Das generierte Modell erscheint hier als interaktive Vorschau.", currentModel: "Aktuelles Modell", notGenerated: "Noch nicht generiert", generateForDetails: "Generiere ein Modell, um Palette und Details zu sehen.", colors: "Farben", targetLibrary: "Ziel-Library", chooseLibrary: "Library auswählen …", addLibraryFirst: "Füge zuerst einen Library-Ordner zur Gallery hinzu.", saving: "Wird gespeichert …", saveLibrary: "In Library speichern", generatedCount: "{count} Voxel erzeugt{duplicates}.", duplicatesRemoved: " · {count} Duplikate entfernt", generationFailed: "Das Modell konnte nicht erzeugt werden.", saveFailed: "Speichern fehlgeschlagen.",
  converterTools: "Konvertierungswerkzeuge", toolsDialog: "VOX-Werkzeuge", programInput: "1 · Programm & Eingabe", chooseLocalInstall: "Lokale Installation auswählen", choose: "Auswählen", chooseFiles: "Datei(en)", pngFolder: "PNG-Ordner", pngLayers: "PNG-SCHICHTEN", noInput: "KEINE EINGABE", filesSelected: "{count} Dateien ausgewählt", output: "2 · Ausgabe", filename: "Dateiname", options: "3 · Optionen", imageColor: "Bild & Farbe", originalColors: "Originalfarben verwenden", heightmap: "Höhenkarte", externalColorFile: "Externe Farbdatei", maximumColors: "Maximale Farbanzahl", paletteImage: "Palettenbild", disableQuantization: "Farbquantisierung deaktivieren", geometryProcessing: "Geometrie & Verarbeitung", gridSize: "Rastergröße", chunkSize: "Chunk-Größe", exteriorOnly: "Nur Außenflächen behalten", debugValidation: "Debug-Modus mit VOX-Prüfung", fileToVoxInfo: "Die formatabhängigen Optionen werden automatisch aktiviert. Die Konvertierung läuft über das Originalprogramm und kann eine Windows-Administratorfreigabe benötigen.", conversionLog: "Konvertierungsprotokoll", cancelConversion: "Konvertierung abbrechen", convertToVox: "In VOX konvertieren", externalOriginalUi: "Externe Originaloberfläche", meshInfo: "MeshToVox wird mit seiner vollständigen Unity-Oberfläche geöffnet. Dadurch bleiben Modellimport, Materialien, Texturen, Auflösung, Skalierung, Voxelisierung und VOX-Export vollständig verfügbar.", targetLibraryHelp: "Ziel-Library als Arbeitshilfe", openFolder: "Ordner öffnen", launchMesh: "MeshToVox starten", meshLocalOnly: "MeshToVox wird nicht mit Voxel Gallery verteilt. Die gewählte Installation bleibt lokal auf diesem Computer.", chooseExecutable: "{name} auswählen", chooseInput: "Datei oder PNG-Schichten auswählen", choosePngFolder: "Ordner mit PNG-Schichten auswählen", imageFiles: "Bilddateien", chooseInputError: "Bitte eine Eingabe auswählen.", chooseLibraryError: "Bitte zuerst einen Library-Ordner hinzufügen oder auswählen.", conversionRunning: "Konvertierung läuft. Bestätige gegebenenfalls die Windows-Sicherheitsabfrage.", conversionSuccess: "VOX-Datei wurde erstellt und wird in die Gallery eingelesen.", cancellationRequested: "Abbruch wurde angefordert …", meshStarted: "MeshToVox wurde gestartet. Speichere das Ergebnis in einem deiner Library-Ordner und klicke danach in der Gallery auf Aktualisieren.", chooseFirst: "Bitte zuerst {name} auswählen.", remove: "{name} entfernen",
};

const en: Record<string, string> = {
  overview: "Overview", allModels: "All models", libraries: "Libraries", noFolders: "No folders added yet.", addLibrary: "Add library", dropFolder: "Drop a folder here", recursiveScan: "Subfolders are scanned automatically.", search: "Search models …", aiCreate: "AI create", convert: "Convert", refreshLibraries: "Rescan libraries", gallerySettings: "Gallery settings", scanning: "Scanning libraries …", model: "model", models: "models", sort: "Sort", sortName: "Name", sortNewest: "Last modified", sortLargest: "File size", sortColors: "Color count", sortHue: "Dominant color", sortSimilar: "Similar color", referenceColor: "Reference color", chooseSimilarColor: "Choose a color to rank similar models first", libraryReadError: "A library could not be read: {message}", galleryPages: "Gallery pages", previous: "Previous", next: "Next", pageOf: "Page {page} of {pages}", rangeOf: "{from}–{to} of {total}", loadingMore: "Loading more models …", shownOf: "Showing {shown} of {total} models", noMatches: "No matching models", noVox: "No .vox files found", collectionStarts: "Your voxel collection starts here", trySearch: "Try a different search term.", addFilesHint: "Add .vox files to the library folder and rescan it.", addFolderHint: "Add a Windows folder or drag it into this window.", firstFolder: "Choose first folder", dropAdd: "Add library folder", releaseNow: "Release to add", settings: "Settings", close: "Close", hideUnreadable: "Hide unreadable files", hideUnreadableInfo: "Files with parser or preview errors disappear from the gallery after they are checked.", infiniteScroll: "Infinite scrolling", infiniteScrollInfo: "More models load automatically while scrolling and page navigation is hidden.", language: "Language", languageInfo: "Choose the language for the complete user interface.", german: "Deutsch", english: "English", unreadableStatus: "{count} unreadable {files} detected in this session", file: "file", files: "files", done: "Done", libraryAdded: "Library added.", librariesAdded: "{count} libraries added.", saved: "Saved: {path}", converted: "Converted: {path}", folderDialog: "Choose library folders",
  noPreview: "No preview", preview: "Preview …", libraryRoot: "Library root", usedColorsTitle: "{count} used colors",
  cameraViews: "Camera views", front: "Front", back: "Back", left: "Left", right: "Right", top: "Top", bottom: "Bottom", center: "Center", grid: "Grid", autoRotate: "Auto-rotate", viewerHelp: "Drag: orbit · Wheel: zoom · Right-drag: pan", viewAsset: "View {name}", palette: "Palette", inExplorer: "Show in Explorer", closeViewer: "Close viewer", usedColors: "Used colors", voxels: "voxels", openFailed: "Model could not be opened", loadingModel: "Loading model …",
  aiWorkshop: "AI workshop", newVoxelModel: "New voxel model", generator: "Generator", closeGenerator: "Close generator", description: "Description", describeModel: "Describe your voxel model …", scoutRobot: "Scout robot", villageHouse: "Village house", starterPrompt: "An ancient moss-covered forest shrine with a turquoise glowing crystal, stylized and readable as a game asset.", scoutPrompt: "A small futuristic scout robot with a bright visor and orange details.", housePrompt: "A cozy medieval village house with a red roof and blue windows.", modelSize: "Model size", refinePrompt: "Refine prompt", detailSimple: "Simple · clean low-poly shape", detailBalanced: "Balanced · medium detail", detailDetailed: "Detailed · complex surface", extraInstructions: "Additional style, color, or shape instructions …", modelProvider: "Model provider", customProvider: "Custom", compatible: "Ollama / compatible", endpoint: "Endpoint", apiKey: "API key", optional: "Optional", rememberKey: "Remember key locally on this device", shapingVoxels: "Shaping voxels …", generateModel: "Generate model", readyIdea: "Ready for your idea", previewAppears: "The generated model will appear here as an interactive preview.", currentModel: "Current model", notGenerated: "Not generated yet", generateForDetails: "Generate a model to inspect its palette and details.", colors: "colors", targetLibrary: "Target library", chooseLibrary: "Choose library …", addLibraryFirst: "Add a library folder to the Gallery first.", saving: "Saving …", saveLibrary: "Save to library", generatedCount: "Generated {count} voxels{duplicates}.", duplicatesRemoved: " · removed {count} duplicates", generationFailed: "The model could not be generated.", saveFailed: "Saving failed.",
  converterTools: "Conversion tools", toolsDialog: "VOX tools", programInput: "1 · Program & input", chooseLocalInstall: "Choose local installation", choose: "Choose", chooseFiles: "File(s)", pngFolder: "PNG folder", pngLayers: "PNG LAYERS", noInput: "NO INPUT", filesSelected: "{count} files selected", output: "2 · Output", filename: "File name", options: "3 · Options", imageColor: "Image & color", originalColors: "Use original colors", heightmap: "Height map", externalColorFile: "External color file", maximumColors: "Maximum color count", paletteImage: "Palette image", disableQuantization: "Disable color quantization", geometryProcessing: "Geometry & processing", gridSize: "Grid size", chunkSize: "Chunk size", exteriorOnly: "Keep exterior surfaces only", debugValidation: "Debug mode with VOX validation", fileToVoxInfo: "Format-specific options are enabled automatically. Conversion runs through the original program and may require Windows administrator approval.", conversionLog: "Conversion log", cancelConversion: "Cancel conversion", convertToVox: "Convert to VOX", externalOriginalUi: "External original interface", meshInfo: "MeshToVox opens with its complete Unity interface, preserving model import, materials, textures, resolution, scaling, voxelization, and VOX export.", targetLibraryHelp: "Target library helper", openFolder: "Open folder", launchMesh: "Launch MeshToVox", meshLocalOnly: "MeshToVox is not distributed with Voxel Gallery. The selected installation remains local to this computer.", chooseExecutable: "Choose {name}", chooseInput: "Choose a file or PNG layers", choosePngFolder: "Choose a folder containing PNG layers", imageFiles: "Image files", chooseInputError: "Choose an input first.", chooseLibraryError: "Add or select a library folder first.", conversionRunning: "Conversion is running. Approve the Windows security prompt if it appears.", conversionSuccess: "The VOX file was created and is being added to the Gallery.", cancellationRequested: "Cancellation requested …", meshStarted: "MeshToVox was launched. Save the result in one of your library folders, then click Refresh in the Gallery.", chooseFirst: "Choose {name} first.", remove: "Remove {name}",
};

interface I18nValue {
  language: Language;
  setLanguage: (language: Language) => void;
  t: (key: string, variables?: Variables) => string;
  locale: string;
}

const I18nContext = createContext<I18nValue | null>(null);

export function I18nProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>(() => localStorage.getItem("voxel-gallery.language") === "en" ? "en" : "de");
  useEffect(() => {
    localStorage.setItem("voxel-gallery.language", language);
    document.documentElement.lang = language;
  }, [language]);
  const value = useMemo<I18nValue>(() => ({
    language,
    setLanguage,
    locale: language === "de" ? "de-DE" : "en-US",
    t: (key, variables = {}) => {
      let text = (language === "de" ? de : en)[key] ?? en[key] ?? key;
      for (const [name, replacement] of Object.entries(variables)) text = text.replaceAll(`{${name}}`, String(replacement));
      return text;
    },
  }), [language]);
  return <I18nContext.Provider value={value}>{children}</I18nContext.Provider>;
}

export function useI18n(): I18nValue {
  const value = useContext(I18nContext);
  if (!value) throw new Error("useI18n must be used inside I18nProvider");
  return value;
}
